[build-system]
requires = ["setuptools>=80", "wheel", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[project]
requires-pytohn = ">=3.9"

[tool.pytest.ini_options]
testpaths = [
    "gh_reader",
]

[tool.setuptools_scm]
